// Code generated by MockGen. DO NOT EDIT.
// Source: keeper-project/internal/store (interfaces: Secret)

// Package mock_store is a generated GoMock package.
package mocks

import (
	context "context"
	types "keeper-project/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSecret is a mock of Secret interface.
type MockCardSecret[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockSecretCardMockRecorder
}

// MockSecretMockRecorderC is the mock recorder for MockSecret.
type MockSecretCardMockRecorder struct {
	mock *MockCardSecret[types.CardInfo]
}

// NewMockCardSecret creates a new mock instance.
func NewMockCardSecret(ctrl *gomock.Controller) *MockCardSecret[types.CardInfo] {
	mock := &MockCardSecret[types.CardInfo]{ctrl: ctrl}
	mock.recorder = &MockSecretCardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardSecret[T]) EXPECT() *MockSecretCardMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCardSecret[T]) Create(arg0 context.Context, arg1, arg2 string, arg3 *types.CardInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSecretCardMockRecorder) Create(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCardSecret[types.CardInfo])(nil).Create), arg0, arg1, arg2, arg3)
}

// Delete mocks base method.
func (m *MockCardSecret[T]) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSecretCardMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCardSecret[types.CardInfo])(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockCardSecret[T]) Get(arg0 context.Context, arg1, arg2 string) (*types.CardInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*types.CardInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSecretCardMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCardSecret[types.CardInfo])(nil).Get), arg0, arg1, arg2)
}

// GetKeysList mocks base method.
func (m *MockCardSecret[T]) GetKeysList(arg0 context.Context, arg1 string) ([]types.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysList", arg0, arg1)
	ret0, _ := ret[0].([]types.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeysList indicates an expected call of GetKeysList.
func (mr *MockSecretCardMockRecorder) GetKeysList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysList", reflect.TypeOf((*MockCardSecret[types.CardInfo])(nil).GetKeysList), arg0, arg1)
}

// Update mocks base method.
func (m *MockCardSecret[T]) Update(arg0 context.Context, arg1, arg2 string, arg3 *types.CardInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSecretCardMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCardSecret[types.CardInfo])(nil).Update), arg0, arg1, arg2, arg3)
}
