// Code generated by MockGen. DO NOT EDIT.
// Source: keeper-project/internal/store (interfaces: Secret)

// Package mock_store is a generated GoMock package.
package mocks

import (
	context "context"
	types "keeper-project/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotesSecret is a mock of Secret interface.
type MockNotesSecret[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockSecretNotesMockRecorder
}

// MockSecretNotesMockRecorderC is the mock recorder for MockSecret.
type MockSecretNotesMockRecorder struct {
	mock *MockNotesSecret[types.Note]
}

// NewMockNotesSecret creates a new mock instance.
func NewMockNotesSecret(ctrl *gomock.Controller) *MockNotesSecret[types.Note] {
	mock := &MockNotesSecret[types.Note]{ctrl: ctrl}
	mock.recorder = &MockSecretNotesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotesSecret[T]) EXPECT() *MockSecretNotesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotesSecret[T]) Create(arg0 context.Context, arg1, arg2 string, arg3 *types.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSecretNotesMockRecorder) Create(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotesSecret[types.Note])(nil).Create), arg0, arg1, arg2, arg3)
}

// Delete mocks base method.
func (m *MockNotesSecret[T]) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSecretNotesMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotesSecret[types.Note])(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockNotesSecret[T]) Get(arg0 context.Context, arg1, arg2 string) (*types.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*types.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSecretNotesMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNotesSecret[types.Note])(nil).Get), arg0, arg1, arg2)
}

// GetKeysList mocks base method.
func (m *MockNotesSecret[T]) GetKeysList(arg0 context.Context, arg1 string) ([]types.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysList", arg0, arg1)
	ret0, _ := ret[0].([]types.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeysList indicates an expected call of GetKeysList.
func (mr *MockSecretNotesMockRecorder) GetKeysList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysList", reflect.TypeOf((*MockNotesSecret[types.Note])(nil).GetKeysList), arg0, arg1)
}

// Update mocks base method.
func (m *MockNotesSecret[T]) Update(arg0 context.Context, arg1, arg2 string, arg3 *types.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSecretNotesMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotesSecret[types.Note])(nil).Update), arg0, arg1, arg2, arg3)
}
