version: '3'

services:
  go-keeper:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ADDRESS: ":8080"
      DATABASE_DSN: "postgresql://keeper:keeper_pass@pg:5432/keeper"
      MINIO_URL: "minio:9000"
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    ports:
      - "8080:8080"
    depends_on:
      - pg
      - minio

  pg:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=keeper
      - POSTGRES_PASSWORD=keeper_pass
      - POSTGRES_DB=keeper
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

  minio:
    container_name: minio
    image: 'bitnami/minio:latest'
    volumes:
      - 'minio_data:/data'
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
  pg_data: